### ISSUE TITLE
build error with h5py when running: python -m pip install tensorflow-macos  

### ISSUE THREAD

**Issue by buffalobillhuang** [mrdbourke/m1-machine-learning-test#4]
(/Users/billhuang/tensorflow-test/env) billhuang@Bills-iMac tensorflow-test % python -m pip install tensorflow-macos                                                 
Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow-macos
  Downloading tensorflow_macos-2.7.0-cp38-cp38-macosx_11_0_arm64.whl (179.0 MB)
     |████████████████████████████████| 179.0 MB 6.7 MB/s             
Collecting h5py>=2.9.0
  Downloading h5py-3.6.0.tar.gz (384 kB)
     |████████████████████████████████| 384 kB 21.8 MB/s            
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/b1/_v80y9pj5x917c_phn4xsk000000gn/T/pip-build-env-5aixvc7e/normal/lib/python3.8/site-packages
  sysconfig: /Library/Python/3.8/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/b1/_v80y9pj5x917c_phn4xsk000000gn/T/pip-build-env-5aixvc7e/normal/lib/python3.8/site-packages
  sysconfig: /Library/Python/3.8/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/b1/_v80y9pj5x917c_phn4xsk000000gn/T/pip-build-env-5aixvc7e/normal'
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/b1/_v80y9pj5x917c_phn4xsk000000gn/T/pip-build-env-5aixvc7e/overlay/lib/python3.8/site-packages
  sysconfig: /Library/Python/3.8/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/b1/_v80y9pj5x917c_phn4xsk000000gn/T/pip-build-env-5aixvc7e/overlay/lib/python3.8/site-packages
  sysconfig: /Library/Python/3.8/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/b1/_v80y9pj5x917c_phn4xsk000000gn/T/pip-build-env-5aixvc7e/overlay'
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting termcolor>=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... done
Collecting keras<2.8,>=2.7.0rc0
  Downloading keras-2.7.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 7.2 MB/s            
Collecting gast<0.5.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 8.9 MB/s             
Collecting protobuf>=3.9.2
  Downloading protobuf-3.19.1-py2.py3-none-any.whl (162 kB)
     |████████████████████████████████| 162 kB 8.2 MB/s            
Collecting tensorflow-estimator<2.8,~=2.7.0rc0
  Downloading tensorflow_estimator-2.7.0-py2.py3-none-any.whl (463 kB)
     |████████████████████████████████| 463 kB 9.4 MB/s            
Requirement already satisfied: wheel<1.0,>=0.32.0 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from tensorflow-macos) (0.33.1)
Collecting keras-preprocessing>=1.1.1
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 2.7 MB/s             
Collecting absl-py>=0.4.0
  Downloading absl_py-1.0.0-py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 12.3 MB/s            
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 6.1 MB/s            
Requirement already satisfied: six>=1.12.0 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from tensorflow-macos) (1.15.0)
Collecting wrapt>=1.11.0
  Downloading wrapt-1.13.3.tar.gz (48 kB)
     |████████████████████████████████| 48 kB 4.8 MB/s             
  Preparing metadata (setup.py) ... done
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting numpy>=1.14.5
  Downloading numpy-1.21.4-cp38-cp38-macosx_11_0_arm64.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 6.3 MB/s            
Collecting flatbuffers<3.0,>=1.12
  Downloading flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.43.0.tar.gz (21.5 MB)
     |████████████████████████████████| 21.5 MB 8.0 MB/s             
  Preparing metadata (setup.py) ... done
Collecting libclang>=9.0.1
  Downloading libclang-12.0.0-py2.py3-none-macosx_11_0_arm64.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 11.4 MB/s            
Collecting typing-extensions>=3.6.6
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting tensorboard~=2.6
  Downloading tensorboard-2.7.0-py3-none-any.whl (5.8 MB)
     |████████████████████████████████| 5.8 MB 16.4 MB/s            
Collecting werkzeug>=0.11.15
  Downloading Werkzeug-2.0.2-py3-none-any.whl (288 kB)
     |████████████████████████████████| 288 kB 7.8 MB/s            
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.3.3-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 7.1 MB/s            
Collecting requests<3,>=2.21.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 4.7 MB/s             
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 10.3 MB/s            
Requirement already satisfied: setuptools>=41.0.0 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow-macos) (49.2.1)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
     |████████████████████████████████| 781 kB 7.5 MB/s            
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 7.1 MB/s            
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.8-py3-none-any.whl (39 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata>=4.4
  Downloading importlib_metadata-4.9.0-py3-none-any.whl (17 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 7.2 MB/s            
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 7.9 MB/s            
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 5.8 MB/s             
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting zipp>=0.5
  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 12.5 MB/s            
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)
     |████████████████████████████████| 146 kB 7.3 MB/s            
Building wheels for collected packages: grpcio, h5py, termcolor, wrapt
  Building wheel for grpcio (setup.py) ... done
  Created wheel for grpcio: filename=grpcio-1.43.0-cp38-cp38-macosx_10_14_arm64.whl size=7189537 sha256=8c59e16fb90c096ccb9c7fb9c2a440c732a99939ba1c1aca00c56f25e44240f6
  Stored in directory: /Users/billhuang/Library/Caches/pip/wheels/75/43/ee/d6fff4bfd9d7a09ea9e81431dd321b13c43a4960b64be34016
  Building wheel for h5py (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Users/billhuang/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/b1/_v80y9pj5x917c_phn4xsk000000gn/T/tmpnzvmgnuw
       cwd: /private/var/folders/b1/_v80y9pj5x917c_phn4xsk000000gn/T/pip-install-a4gv3n4i/h5py_1db389eb844d4445a327409d3e9fb83a
  Complete output (70 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-arm64-3.8
  creating build/lib.macosx-10.14-arm64-3.8/h5py
  copying h5py/h5py_warnings.py -> build/lib.macosx-10.14-arm64-3.8/h5py
  copying h5py/version.py -> build/lib.macosx-10.14-arm64-3.8/h5py
  copying h5py/__init__.py -> build/lib.macosx-10.14-arm64-3.8/h5py
  copying h5py/ipy_completer.py -> build/lib.macosx-10.14-arm64-3.8/h5py
  creating build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/files.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/compat.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/__init__.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/selections.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/dataset.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/vds.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/selections2.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/group.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/datatype.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/attrs.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/dims.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/base.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  copying h5py/_hl/filters.py -> build/lib.macosx-10.14-arm64-3.8/h5py/_hl
  creating build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_dimension_scales.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_attribute_create.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_file_image.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/conftest.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_h5f.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_dataset_getitem.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_group.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_errors.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_dataset_swmr.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_slicing.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_h5pl.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_attrs.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/__init__.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_attrs_data.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_h5t.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_big_endian_file.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_h5p.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_h5o.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_datatype.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/common.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_dataset.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_file.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_selections.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_dtype.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_h5.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_file2.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_completions.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_filters.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_base.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  copying h5py/tests/test_objects.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests
  creating build/lib.macosx-10.14-arm64-3.8/h5py/tests/data_files
  copying h5py/tests/data_files/__init__.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests/data_files
  creating build/lib.macosx-10.14-arm64-3.8/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests/test_vds
  copying h5py/tests/test_vds/__init__.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.macosx-10.14-arm64-3.8/h5py/tests/test_vds
  copying h5py/tests/data_files/vlen_string_s390x.h5 -> build/lib.macosx-10.14-arm64-3.8/h5py/tests/data_files
  copying h5py/tests/data_files/vlen_string_dset_utc.h5 -> build/lib.macosx-10.14-arm64-3.8/h5py/tests/data_files
  copying h5py/tests/data_files/vlen_string_dset.h5 -> build/lib.macosx-10.14-arm64-3.8/h5py/tests/data_files
  running build_ext
  Building h5py requires pkg-config unless the HDF5 path is explicitly specified
  error: pkg-config probably not installed: FileNotFoundError(2, 'No such file or directory')
  ----------------------------------------
  ERROR: Failed building wheel for h5py
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=3d21bd58f207bea71ef3b49fe19d4ea57d1bb49d26196616149eb58d39179173
  Stored in directory: /Users/billhuang/Library/Caches/pip/wheels/a0/16/9c/5473df82468f958445479c59e784896fa24f4a5fc024b0f501
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.13.3-cp38-cp38-macosx_10_14_arm64.whl size=47927 sha256=fb991bad4a02f68b0b583041b67089acb2d1e6ddc48646eb63b37ad3b015ff4a
  Stored in directory: /Users/billhuang/Library/Caches/pip/wheels/bb/05/57/f0c531fdf04b11be18b21ab4d1ec5586a6897caa6710c2a1a5
Successfully built grpcio termcolor wrapt
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects

**Comment by buffalobillhuang** [comment]
The machine is a M1 iMac. Before doing the step-by-stepy instruction, this machine already has a python installed:
 (/Users/billhuang/tensorflow-test/env) billhuang@Bills-iMac tensorflow-test % python --version
Python 3.8.9
(/Users/billhuang/tensorflow-test/env) billhuang@Bills-iMac tensorflow-test % which python
python: aliased to /usr/bin/python3

**Comment by buffalobillhuang** [comment]
tried with a system-wide python 3.9 as well. Same problem.

**Comment by buffalobillhuang** [comment]
I wonder whether this is an iMac issue? Appreciate any help. Thanks

**Comment by buffalobillhuang** [comment]
I have figured out how to fix this --- this is close-able now.

**Comment by gschoeni** [comment]
@buffalobillhuang what was the fix?

**Comment by StarPlatinum0** [comment]
你说你🐎呢

**Comment by dasiemens-coder** [comment]
Hey I ended up with the same issue, @buffalobillhuang can you share your solution. Much appreciated
