### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow-macos

### ISSUE THREAD

**Issue by ivy113** [mrdbourke/m1-machine-learning-test#9]
Hi, 

Not really sure where the error is coming from, but I am getting the following error. 
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos

Followed everything in your tutorial up to part 5 without any problems.

**Comment by mrdbourke** [comment]
Hi Ivy,

I think you'll solve this by installing Python 3.8 as the base environment setup: 

Step 6:
```
conda create --prefix ./env
conda activate ./env
```

**Comment by ivy113** [comment]
Noted! I got this to work, and am able to import tensorflow in jupyterlab (completed up to step 13).
However, in vscode, in the same conda env previously created, I still get no module named 'tensorflow' when I try to import...

**Comment by mrdbourke** [comment]
Hmmm, did you activate the environment when using VS Code?
